version: '3.9'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data_a:/data
    entrypoint: redis-server --appendonly yes
    
volumes:
  redis_data_a:

networks:
  default:
    name: scrappy_schedule_network