# Generated by Django 5.1.5 on 2025-01-20 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('price_raw', models.CharField(max_length=20)),
                ('price_text', models.CharField(max_length=20)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductScapeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('metadata', models.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_scape_events', to='products.products')),
            ],
        ),
    ]
