# Generated by Django 5.1.5 on 2025-01-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='asin',
            field=models.CharField(db_index=True, max_length=120, unique=True),
        ),
    ]
