# Generated by Django 5.1.5 on 2025-01-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_asin'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
