# Generated by Django 5.1.5 on 2025-01-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='_trigger_scrape',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='trigger_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
