# Generated by Django 5.1.5 on 2025-01-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products__trigger_scrape_products_trigger_scrape'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='_trigger_scrape',
        ),
        migrations.RemoveField(
            model_name='products',
            name='trigger_scrape',
        ),
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True, help_text='scape daily?'),
        ),
    ]
